### ISSUE TITLE
Some Puzzle about QBO-Metrics

### ISSUE THREAD

**Issue by ligeer76** [vschenzinger/QBO-Metrics#1]
Dear Dr. Verena Schenzinger，
I am Qitao Cui, a postgraduate student in the Institute of Atmospheric Physics(China). 
 Recently I read your code QBO-Metrics on github. It is exciting to find such a good method to deal with the QBO analysis!
	When running the code, I noticed that the var “cal” is very important but I can’t figure out its’ proper form. Now I have a dataset about zonal mean T and U during 1979-1990 (monthly data). I assume the var “cal” is 197901,197902…199012.But it seems not helpful for the debug.
	I wonder if there is a correct form to set the var “cal” ? Could you please show me an example or  details about it? 
	Perhaps my understanding is still unsufficient, any suggestions and reply are very precious. I would appreciate it!

Best wishes,
Qitao Cui
Institute of Atmospheric Physics
Chinese Academy of Sciences
Beijing

**Comment by vschenzinger** [comment]
Dear Qitao Cui,

as commented at the beginning of the code, "cal" is indeed referring to the time axis and should be in years, i.e. January 1979 (197901) = 1979.0, 197902 = 1979.0 + 1/12. and so on (I just put one month as 1/12 of a year even though it is not exact, it is good enough for this kind of analysis and one does not have to fiddle with different number of days per month)
Hope this helps!
Good luck with your PhD!

Best wishes,
Verena

**Comment by ligeer76** [comment]
> Dear Qitao Cui,
> 
> as commented at the beginning of the code, "cal" is indeed referring to the time axis and should be in years, i.e. January 1979 (197901) = 1979.0, 197902 = 1979.0 + 1/12. and so on (I just put one month as 1/12 of a year even though it is not exact, it is good enough for this kind of analysis and one does not have to fiddle with different number of days per month) Hope this helps! Good luck with your PhD!
> 
> Best wishes, Verena

Thanks for your reply! Yeah, I tried the form you mentioned, because I noticed the plot script and the func _get_period_ so I guess maybe "197902 = 1979.0 + 1/12" is the proper. So I close this issue in advance.
Thanks again, your codes help me! Have a good day!

Best wishes,
Qitao Cui
